/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Abm: typeof import('./src/components/package/Abm/Abm.vue')['default']
    ActionBar: typeof import('./src/components/package/ActionBar/ActionBar.vue')['default']
    BAvatar: typeof import('bootstrap-vue-next')['BAvatar']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BOverlay: typeof import('bootstrap-vue-next')['BOverlay']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    Button: typeof import('./src/components/package/Button/Button.vue')['default']
    ButtonTest: typeof import('./src/components/package/ButtonTest/ButtonTest.vue')['default']
    CheckBox: typeof import('./src/components/package/CheckBox/CheckBox.vue')['default']
    Date: typeof import('./src/components/package/Date/Date.vue')['default']
    Dialog: typeof import('./src/components/package/Dialog/Dialog.vue')['default']
    ErrorsForm: typeof import('./src/components/package/ErrorsForm/ErrorsForm.vue')['default']
    File: typeof import('./src/components/package/File/File.vue')['default']
    Form: typeof import('./src/components/package/Form/Form.vue')['default']
    FormFile: typeof import('./src/components/package/FormFile/FormFile.vue')['default']
    Input: typeof import('./src/components/package/Input/Input.vue')['default']
    ItemSideBar: typeof import('./src/components/package/ItemSideBar/ItemSideBar.vue')['default']
    Layout: typeof import('./src/components/package/Layout/Layout.vue')['default']
    ModalForm: typeof import('./src/components/package/ModalForm/ModalForm.vue')['default']
    MultipleForm: typeof import('./src/components/package/MultipleForm/MultipleForm.vue')['default']
    NavBar: typeof import('./src/components/package/NavBar/NavBar.vue')['default']
    Overlay: typeof import('./src/components/package/Overlay/Overlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/package/Select/Select.vue')['default']
    SideBar: typeof import('./src/components/package/SideBar/SideBar.vue')['default']
    TabBar: typeof import('./src/components/package/TabBar/TabBar.vue')['default']
    Table: typeof import('./src/components/package/Table/Table.vue')['default']
    TextArea: typeof import('./src/components/package/TextArea/TextArea.vue')['default']
  }
}
