version: "3.7"

services:
  corporation:
    container_name: corporation
    build:
      context: .
      dockerfile: dockerfile
    command: sh /var/www/html/node_start.sh
    volumes:
      - ./:/var/www/html
    ports:
      - 3004:3004

    working_dir: /var/www/html
    networks:
      - mysql_net
networks:
  mysql_net:
    external: true
    name: mysql_net

